#!/bin/bash

set -e

echo "Pushing additional tags"
imageName=$DOCKER_REPO":nightly-20171010-0759"
docker tag $IMAGE_NAME $imageName
docker push $imageName

imageName=$DOCKER_REPO":4.0.0-nightly-20171010-0759"
docker tag $IMAGE_NAME $imageName
docker push $imageName